

SELECT CUST_NUM
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);



SELECT O.CUST_NUM, O.ORDER_ID
FROM dbo.ORDERS O
WHERE O.CUST_NUM IN (
    SELECT C.CUST_NUM
    FROM dbo.CUSTOMERS C
    WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
);



SELECT O.CUST_NUM, O.ORDER_ID, O.ORDER_DATE
FROM dbo.ORDERS O
WHERE O.ORDER_DATE = (
    SELECT MAX(O2.ORDER_DATE)
    FROM dbo.ORDERS O2
    WHERE O2.CUST_NUM IN (
        SELECT C.CUST_NUM
        FROM dbo.CUSTOMERS C
        WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
    )
)
AND O.CUST_NUM IN (
    SELECT C.CUST_NUM
    FROM dbo.CUSTOMERS C
    WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
);

