USE WebStor

/* Завдання 1 */
SELECT CUST_NUM
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

/* Завдання 2 */
SELECT O.CUST, O.ORDER_NUM
FROM dbo.ORDERS O
JOIN dbo.CUSTOMERS C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

/* Завдання 3 */
SELECT O.CUST, O.ORDER_NUM, O.ORDER_DATE
FROM dbo.ORDERS O
JOIN dbo.CUSTOMERS C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
AND O.ORDER_DATE = (SELECT MAX(O2.ORDER_DATE)
FROM dbo.ORDERS O2
JOIN dbo.CUSTOMERS C2 ON O2.CUST = C2.CUST_NUM
WHERE C2.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS));

