USE WebStor1

SELECT CUST_NUM
FROM [dbo].[CUSTOMERS]
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS]);

SELECT O.[ORDER_NUM], O.[CUST]
FROM [dbo].[ORDERS] O
WHERE O.[CUST] IN (
    SELECT C.[CUST_NUM]
    FROM [dbo].[CUSTOMERS] C
    WHERE C.[CREDIT_LIMIT] = (SELECT MAX([CREDIT_LIMIT]) FROM [dbo].[CUSTOMERS])
);

SELECT TOP 1 O.[ORDER_NUM], O.[CUST], O.[ORDER_DATE]
FROM [dbo].[ORDERS] O
WHERE O.[CUST] IN (
    SELECT C.[CUST_NUM]
    FROM [dbo].[CUSTOMERS] C
    WHERE C.[CREDIT_LIMIT] = (SELECT MAX([CREDIT_LIMIT]) FROM [dbo].[CUSTOMERS])
)
ORDER BY O.[ORDER_DATE] DESC;