SELECT CUST_NUM
FROM DBO.CUSTOMERS 
WHERE CREDIT_LIMIT=(SELECT MAX(CREDIT_LIMIT) FROM DBO.CUSTOMERS);


SELECT O.ORDER_NUM, O.CUST
FROM DBO.ORDERS O
WHERE O.CUST IN (SELECT C.CUST_NUM FROM DBO.CUSTOMERS C WHERE C.CREDIT_LIMIT=(SELECT MAX(CREDIT_LIMIT) FROM DBO.CUSTOMERS));


SELECT TOP 1 O.ORDER_NUM, O.CUST, O.ORDER_DATE
FROM DBO.ORDERS O
WHERE O.CUST IN (SELECT C.CUST_NUM FROM DBO.CUSTOMERS C WHERE C.CREDIT_LIMIT=(SELECT MAX(CREDIT_LIMIT) FROM DBO.CUSTOMERS))
ORDER BY O.ORDER_DATE DESC;
