USE WebStor
-- 1завдання--
SELECT MANAGER, NAME, AGE, TITLE
FROM [dbo].[SALESREPS]
WHERE AGE>45
ORDER BY AGE DESC;
--2завдання--
SELECT DISTINCT MFR, PRODUCT
FROM [dbo].[ORDERS]
WHERE ORDER_DATE BETWEEN '2008-01-01' AND '2008-12-31'
;
--3завдання--
SELECT TOP 1 WITH TIES REP, COUNT(*) AS QTY_ORDERS
FROM [dbo].[ORDERS]
WHERE ORDER_DATE BETWEEN '2008-01-01' AND '2008-12-31'
GROUP BY REP
ORDER BY QTY_ORDERS DESC;