/* Завдання 1 */

SELECT EMPL_NUM, NAME, AGE, TITLE 
FROM SALESREPS
WHERE Age > 45
ORDER BY  Age DESC;

/* Завдання 2 */

SELECT DISTINCT MFR, PRODUCT 
FROM ORDERS
WHERE YEAR(ORDER_DATE) = 2008;

/* Завдання 3 */

SELECT TOP 1 WITH TIES REP, COUNT(*) 
FROM ORDERS
WHERE YEAR(ORDER_DATE) = 2008
GROUP BY REP
ORDER BY COUNT(*) DESC;