/*Завдання 1*/
SELECT EMPL_NUM, NAME, AGE, TITLE
FROM [dbo].[SALESREPS]
WHERE AGE > 45
ORDER BY AGE DESC;

/*Завдання 2*/
SELECT DISTINCT MFR, PRODUCT
FROM [dbo].[ORDERS3]
WHERE YEAR(ORDER_DATE) = 2008;

/*Завдання 3*/
SELECT TOP 1 WITH TIES REP, COUNT(*) AS OrderCount
FROM [dbo].[ORDERS3]
WHERE YEAR(ORDER_DATE) = 2008
GROUP BY REP
ORDER BY COUNT(*) DESC;

