SELECT 
    OFFICE, 
    CITY, 
    MGR
FROM 
    [dbo].[OFFICES]
WHERE 
    Region = 'Eastern' AND 
    SALES <= 350000.00;
SELECT *
FROM 
    [dbo].[ORDERS]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 AND 
    (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');
SELECT 
    MFR AS ORDER_NUM, 
    COUNT(DISTINCT ORDER_DATE) AS QTY
FROM 
    [dbo].[ORDERS]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 AND 
    (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    QTY ASC;
SELECT TOP 1 WITH TIES
    ORDER_NUM,
    SUM(QTY) AS TOTAL_SUM
FROM
    [dbo].[ORDERS] o
WHERE
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 AND 
    (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY
    ORDER_NUM
ORDER BY
    TOTAL_SUM DESC;

SELECT TOP 1 WITH TIES 
    REP_OFFICE AS EMPL_NUM, 
    COUNT(*) AS EmployeeCount
FROM 
    [dbo].[SALESREPS]
WHERE 
    TITLE = 'Sales Rep' AND 
    AGE IN (29, 45, 48)
GROUP BY 
    REP_OFFICE
ORDER BY 
    EmployeeCount DESC;

SELECT TOP 1 WITH TIES
    MFR_ID AS ManufacturerID,
    PRODUCT_ID AS ProductID,
    DESCRIPTION AS ProductDescription,
    LEN(DESCRIPTION) AS DescriptionLength
FROM 
    [dbo].[PRODUCTS]
ORDER BY 
    LEN(DESCRIPTION) DESC;

SELECT DISTINCT
    RTRIM(CONCAT_WS(' ', MFR_ID, PRODUCT_ID, [DESCRIPTION])) AS ConcatenatedString,
    LEN(RTRIM(CONCAT_WS(' ', MFR_ID, PRODUCT_ID, [DESCRIPTION]))) AS StringLength
FROM 
    [dbo].[PRODUCTS]
WHERE 
    PRODUCT_ID NOT LIKE '%[^0-9]%' 
ORDER BY 
    StringLength DESC;

WITH CustomerCredit AS (
    SELECT 
        CUST_NUM,
        COMPANY,
        CREDIT_LIMIT,
        ROW_NUMBER() OVER (ORDER BY CREDIT_LIMIT ASC) AS RowNum
    FROM [dbo].[CUSTOMERS]
)
SELECT 
    CUST_NUM,
    CONCAT(
        LEFT(COMPANY, 2), 
        REPLICATE('*', LEN(COMPANY) - 4), 
        RIGHT(COMPANY, 2)
    ) AS MaskedCustomerName,
    CREDIT_LIMIT
FROM CustomerCredit
WHERE CREDIT_LIMIT = (SELECT MIN(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS]);
