
USE WebStor;

SELECT OFFICE, CITY, MGR
FROM dbo.OFFICES
WHERE REGION = 'East' 
AND TARGET <= 350000.00;




   SELECT *
FROM [dbo].[ORDERS]
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 
AND(PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');




SELECT MFR,COUNT(DISTINCT ORDER_NUM) AS UNIQUE_ORDERS,
    SUM(AMOUNT) AS TOTAL_SUM
FROM [dbo].[ORDERS]
WHERE  YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 AND
         (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY TOTAL_SUM ASC;




WITH TotalSums AS (
SELECT MFR, SUM(AMOUNT) AS TOTAL_SUM
FROM  [dbo].[ORDERS]
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008 AND
        (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY  MFR
)
SELECT TOP 1 WITH TIES MFR, TOTAL_SUM
FROM TotalSums
ORDER BY TOTAL_SUM DESC;




SELECT TOP 1 WITH TIES  REP_OFFICE AS OFFICE_ID,
    COUNT(EMPL_NUM) AS EMPLOYEE_COUNT
FROM [dbo].[SALESREPS]
WHERE TITLE = 'Sales Rep' AND AGE IN (29, 45, 48)
GROUP BY REP_OFFICE
ORDER BY EMPLOYEE_COUNT DESC;




SELECT TOP 1 WITH TIES MFR_ID, PRODUCT_ID, [DESCRIPTION], LEN([DESCRIPTION]) AS DESCRIPTION_LENGTH
FROM [dbo].[PRODUCTS]
ORDER BY DESCRIPTION_LENGTH DESC;




SELECT DISTINCT CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS CONCATENATED_STRING,
                LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION]))) AS STRING_LENGTH
FROM [dbo].[PRODUCTS]
WHERE  PRODUCT_ID NOT LIKE '%[^0-9]%'
ORDER BY STRING_LENGTH DESC;





SELECT CUST_NUM AS CUSTOMER_ID, 
       LEFT(COMPANY, 2) + REPLICATE('*', LEN(COMPANY) - 4) + RIGHT(COMPANY, 2) AS MASKED_NAME,
       CREDIT_LIMIT
FROM DBO.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MIN(CREDIT_LIMIT) FROM DBO.CUSTOMERS);
