USE WebStor

-- ¹1
SELECT [OFFICE], [CITY], [MGR]
FROM [dbo].[OFFICES]
WHERE Region = 'Eastern' AND TARGET <= 350000.00;

-- ¹2
SELECT [ORDER_NUM], [ORDER_DATE],[CUST], [REP], [MFR], [PRODUCT], [QTY], [AMOUNT]
FROM [dbo].[ORDERS]
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');
  SELECT [MFR],
Count(Distinct [ORDER_NUM]) as Orders,
SUM(AMOUNT) as TotalOrderAmount
FROM [dbo].[ORDERS]
WHERE YEAR(Order_Date) NOT BETWEEN 2008 AND 2008
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY [MFR]
ORDER BY TotalOrderAmount  ASC;
SELECT TOP 1 WITH TIES [MFR], SUM(Amount) AS TotalOrderAmount
FROM [dbo].[ORDERS]
WHERE YEAR(Order_Date) NOT BETWEEN 2008 AND 2008
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY [MFR]
ORDER BY TotalOrderAmount DESC;

--¹3
SELECT TOP 1 WITH TIES [MFR], SUM(Amount) AS TotalOrderAmount
FROM [dbo].[ORDERS]
WHERE YEAR(Order_Date) NOT BETWEEN 2008 AND 2008
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY [MFR]
ORDER BY TotalOrderAmount DESC;

--¹4
SELECT TOP 1 WITH TIES MFR_ID, PRODUCT_ID, [DESCRIPTION], LEN([DESCRIPTION]) AS DescriptionLength
FROM [dbo].[PRODUCTS]
ORDER BY LEN([DESCRIPTION]) DESC;

--¹5
SELECT DISTINCT CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS ConcatenatedString,
                LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION]))) AS StringLength
FROM [dbo].[PRODUCTS]
WHERE PRODUCT_ID NOT LIKE '%[^0-9]%'
ORDER BY StringLength DESC;

--¹6
SELECT [CUST_NUM], 
       CONCAT(
           LEFT([COMPANY], 2), 
           REPLICATE('*', LEN([COMPANY]) - 4), 
           RIGHT([COMPANY], 2)
       ) AS MaskedName,
       [Credit_Limit]
FROM [dbo].[CUSTOMERS]
WHERE [Credit_Limit] = (SELECT MIN(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS]);