SELECT *
FROM [dbo].[OFFICES];

SELECT OFFICE, CITY, MGR
FROM [dbo].[OFFICES]
WHERE Region = 'Eastern' 
AND TARGET <= 350000.00;

SELECT *
FROM [dbo].[ORDERS]
WHERE YEAR(ORDER_DATE) NOT BETWEEN '2008' AND '2008'
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');

SELECT MFR, COUNT(DISTINCT ORDER_NUM) AS UniqueOrders, SUM(AMOUNT) AS TotalAmount
FROM dbo.ORDERS
WHERE YEAR(ORDER_DATE) NOT BETWEEN '2008' AND '2008'
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY SUM(AMOUNT) ASC;

SELECT TOP 1 WITH TIES MFR, SUM(Amount) AS TotalSales
FROM [dbo].[ORDERS]
WHERE YEAR(ORDER_DATE) NOT BETWEEN '2008' AND '2008'
AND (Product LIKE '_A%' OR Product LIKE '%0%')
GROUP BY MFR
ORDER BY SUM(Amount) DESC;

SELECT *
FROM [dbo].[SALESREPS]

SELECT TOP 1 WITH TIES REP_OFFICE, COUNT(empl_num) AS EmployeeCount
FROM [dbo].[SALESREPS]
WHERE TITLE = 'Sales Rep' AND Age IN (29, 45, 48)
GROUP BY REP_OFFICE
ORDER BY COUNT(empl_num) DESC;

SELECT *
FROM [dbo].[PRODUCTS]

SELECT TOP 1 WITH TIES MFR_ID, PRODUCT_ID Description, LEN(Description) AS DescriptionLength
FROM [dbo].[PRODUCTS]
ORDER BY LEN(Description) DESC;

SELECT DISTINCT CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS ConcatenatedString,
       LEN(RTRIM(CONCAT_WS(' ', MFR_ID, PRODUCT_ID, [DESCRIPTION]))) AS StringLength
FROM [dbo].[PRODUCTS]
WHERE PRODUCT_ID NOT LIKE '%[^0-9]%'
ORDER BY StringLength DESC;

SELECT *
FROM [dbo].[CUSTOMERS]

SELECT CUST_NUM AS COSTUMER_ID, 
       LEFT(COMPANY, 2) + REPLICATE('*', LEN(COMPANY) - 4) + RIGHT(COMPANY, 2) AS MASKED_NAME,
       CREDIT_LIMIT
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MIN(credit_limit) FROM dbo.CUSTOMERS);




