Use WebStor

SELECT 
    OFFICE AS OFFICE_ID, 
    CITY, 
    MGR AS MGR_ID
FROM 
    [dbo].[OFFICES]
WHERE 
    REGION = 'East' 
    AND TARGET <= 350000.00;

SELECT *
FROM 
    [dbo].[ORDERS3]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');



SELECT 
    MFR, 
    COUNT(DISTINCT ORDER_NUM) AS UNIQUE_ORDERS, 
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM 
    [dbo].[ORDERS3]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    TOTAL_AMOUNT ASC;


SELECT TOP 1 WITH TIES 
    MFR, 
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM 
    [dbo].[ORDERS3]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    TOTAL_AMOUNT DESC;


SELECT TOP 1 WITH TIES 
    REP_OFFICE AS OFFICE_ID, 
    COUNT(*) AS EMPLOYEE_COUNT
FROM 
    [dbo].[SALESREPS]
WHERE 
    TITLE = 'Sales Rep' 
    AND AGE IN (29, 45, 48)
GROUP BY 
    REP_OFFICE
ORDER BY 
    EMPLOYEE_COUNT DESC;



SELECT TOP 1 WITH TIES 
    MFR_ID, 
    PRODUCT_ID, 
    [DESCRIPTION], 
    LEN([DESCRIPTION]) AS DESCRIPTION_LENGTH
FROM 
    [dbo].[PRODUCTS]
ORDER BY 
    DESCRIPTION_LENGTH DESC;


SELECT DISTINCT 
    CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS CONCATENATED_STRING,
    LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION]))) AS STRING_LENGTH
FROM 
    [dbo].[PRODUCTS]
WHERE 
    PRODUCT_ID NOT LIKE '%[^0-9]%'  -- перевірка, що PRODUCT_ID містить лише цифри
ORDER BY 
    STRING_LENGTH DESC;



SELECT TOP 1 WITH TIES 
    CUST_NUM AS CUSTOMER_ID, 
    COMPANY AS CUSTOMER_NAME, 
    CREDIT_LIMIT
FROM 
    [dbo].[CUSTOMERS3]
ORDER BY 
    CREDIT_LIMIT ASC;



















