SELECT*
FROM dbo.OFFICES

SELECT*
FROM dbo.ORDERS

SELECT*
FROM dbo.SALESREPS

SELECT*
FROM dbo.PRODUCTS

SELECT*
FROM dbo.CUSTOMERS

/*TASK 1*/
SELECT OFFICE, CITY, MGR
FROM dbo.OFFICES
WHERE TARGET<=350000 AND REGION='Eastern'
;
/*TASK 2.1*/
SELECT*
FROM dbo.ORDERS
WHERE ORDER_DATE NOT BETWEEN '20080101' AND '20081231' 
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
;
/*TASK 2.2*/
SELECT MFR, COUNT(DISTINCT PRODUCT) AS UNIQUE_ORDERS, 
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM dbo.ORDERS
WHERE 
    ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    TOTAL_AMOUNT ASC;
/*TASK 2.3*/
SELECT TOP 1 WITH TIES 
    MFR, 
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM 
    [dbo].[ORDERS]
WHERE 
    ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    TOTAL_AMOUNT DESC;
/*TASK 3*/
SELECT TOP 1 WITH TIES 
    REP_OFFICE, 
    COUNT(*) AS EMPL_COUNT
FROM 
    [dbo].[SALESREPS]
WHERE 
    TITLE = 'Sales Rep'
    AND age IN (29, 45, 48)
GROUP BY 
    REP_OFFICE
ORDER BY 
    EMPL_COUNT DESC;
/*TASK 4*/
SELECT TOP 1 WITH TIES
    MFR_ID,
    PRODUCT_ID,
    DESCRIPTION,
    LEN(DESCRIPTION) AS DESCRIPTION_LEN
FROM 
    [dbo].[PRODUCTS]
ORDER BY 
    DESCRIPTION_LEN DESC;
/*TASK 5*/
SELECT 
    DISTINCT RTRIM(CONCAT_WS(' ', UPPER(MFR_ID), PRODUCT_ID, [DESCRIPTION])) AS CONCAT_STR,
    LEN(RTRIM(CONCAT_WS(' ', UPPER(MFR_ID), PRODUCT_ID, [DESCRIPTION]))) AS CONCAT_LEN
FROM 
    [dbo].[PRODUCTS]
WHERE 
    product_id NOT LIKE '%[^0-9]%'
ORDER BY 
    CONCAT_LEN DESC;
/*TASK 6*/
SELECT TOP 1 WITH TIES
    CUST_NUM, 
	CONCAT(
        SUBSTRING(COMPANY, 1, 2), 
        REPLICATE('*', LEN(COMPANY) - 4), SUBSTRING(COMPANY, LEN(COMPANY) - 1,2)) AS HIDDEN_NAME,
    MIN(CREDIT_LIMIT) AS MIN_CREDIT_LIMIT
FROM DBO.CUSTOMERS
GROUP BY CUST_NUM, COMPANY
ORDER BY MIN_CREDIT_LIMIT
;

    













