USE WebStor1

SELECT OFFICE, 
CITY, 
MGR
FROM 
[dbo].[OFFICES]
WHERE 
REGION = 'East' 
AND TARGET <= 350000.00;

SELECT* 
FROM 
[dbo].[ORDERS]
WHERE 
YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');

SELECT 
    MFR, 
    COUNT(DISTINCT ORDER_NUM) AS UNIQUE_ORDERS, 
    SUM(ORDER_NUM) AS TOTAL_SUM
FROM 
    [dbo].[ORDERS]
WHERE 
    YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY 
    MFR
ORDER BY 
    TOTAL_SUM ASC;

	WITH TOTALS AS (
    SELECT 
        MFR, 
        SUM(ORDER_NUM) AS TOTAL_SUM
    FROM 
        [dbo].[ORDERS]
    WHERE 
        YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
        AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
    GROUP BY 
        MFR
)
SELECT 
    MFR, 
    TOTAL_SUM
FROM 
    TOTALS
WHERE 
    TOTAL_SUM = (SELECT MAX(TOTAL_SUM) FROM TOTALS);

	SELECT TOP (1) WITH TIES
    REP_OFFICE, 
    COUNT(*) AS EMPLOYEE_COUNT
FROM 
    [dbo].[SALESREPS]
WHERE 
    MANAGER = 'Sales Rep' 
    AND AGE IN (29, 45, 48)
GROUP BY 
    REP_OFFICE
ORDER BY 
    EMPLOYEE_COUNT DESC;

	SELECT  MFR_ID, PRODUCT_ID, 
    [DESCRIPTION], 
    LEN([DESCRIPTION]) AS DESCRIPTION_LENGTH
FROM 
    [dbo].[PRODUCTS]
WHERE 
    LEN([DESCRIPTION]) = (SELECT MAX(LEN([DESCRIPTION])) FROM [dbo].[PRODUCTS]);

	SELECT 
    DISTINCT 
    CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS CONCATENATED_STRING,
    LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION]))) AS STRING_LENGTH
FROM 
    [dbo].[PRODUCTS]
WHERE 
    PRODUCT_ID NOT LIKE '%[^0-9]%'
ORDER BY 
    STRING_LENGTH DESC;

	SELECT CUST_NUM AS customer_id, 
       LEFT(company, 2) + REPLICATE('*', LEN(company) - 4) + RIGHT(company, 2) AS masked_name,
       credit_limit
FROM dbo.CUSTOMERS
WHERE credit_limit = (SELECT MIN(credit_limit) FROM dbo.CUSTOMERS);