USE WebStor
SELECT* 
FROM dbo.OFFICES
WHERE REGION = 'Eastern' and TARGET <=350000.00;

SELECT*
FROM dbo.ORDERS
WHERE YEAR(ORDER_DATE) <> 2008
AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');

SELECT MFR, COUNT(DISTINCT ORDER_NUM) as UniqueORDERS, SUM(AMOUNT) AS TotalAmount
FROM dbo.ORDERS 
WHERE YEAR(ORDER_DATE) <> 2008 AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR 
ORDER BY TotalAmount ASC;

SELECT TOP 1 WITH TIES MFR, SUM(AMOUNT) AS TotalAmount
FROM dbo.ORDERS 
WHERE YEAR(ORDER_DATE) <> 2008 AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR 
ORDER BY TotalAmount DESC;

SELECT TOP 1 WITH TIES rep_office AS office_id, COUNT(empl_num) AS employee_count
FROM dbo.SALESREPS 
WHERE TITLE = 'Sales Rep' and AGE IN (29, 45, 48) 
GROUP BY REP_OFFICE
ORDER BY employee_count DESC;


SELECT TOP 1 WITH TIES MFR_ID, PRODUCT_ID, DESCRIPTION, LEN(DESCRIPTION) AS DESCRIPTION_LENGTH
FROM dbo.PRODUCTS
ORDER BY DESCRIPTION_LENGTH DESC;

SELECT DISTINCT CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM(DESCRIPTION)) AS CONCATENATED_STRING,
  LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM(DESCRIPTION))) AS CONCATENATED_LENGTH
FROM dbo.PRODUCTS 
WHERE PRODUCT_ID NOT LIKE '%(^0-9)%'
ORDER BY CONCATENATED_LENGTH DESC;

SELECT CUST_NUM AS CUSTOMER_ID, LEFT(COMPANY, 2) + REPLICATE('*', LEN(COMPANY)-4)+RIGHT(COMPANY, 2) AS MASKED_NAME, CREDIT_LIMIT
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT=(SELECT MIN(CREDIT_LIMIT) FROM dbo.CUSTOMERS); 
