

SELECT DISTINCT O.MFR
FROM dbo.ORDERS O
INNER JOIN dbo.CUSTOMERS C ON c.CUST_NUM = C.CUST_NUM
WHERE O.ORDER_DATE BETWEEN '2008-01-01' AND '2008-12-31'
  AND C.COMPANY LIKE '%CORP%';


  SELECT 
    C.CUST_NUM,
    MONTH(O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O ON C.CUST_NUM = O.CUST
  AND O.ORDER_DATE BETWEEN '2008-01-01' AND '2008-12-31'
  AND C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UNIQUE_ORDERS DESC;


SELECT 
    c.CUST_NUM,
    UPPER(c.COMPANY) AS CompanyName,
    p.DESCRIPTION AS ProductDescription
FROM dbo.CUSTOMERS c
LEFT JOIN dbo.ORDERS o ON c.CUST_NUM = o.CUST
    AND o.ORDER_DATE BETWEEN '20080101' AND '20081231'
    AND c.COMPANY LIKE '%CORP%'
LEFT JOIN dbo.PRODUCTS p ON o.PRODUCT = p.PRODUCT_ID
WHERE c.CUST_NUM IS NOT NULL;