SELECT DISTINCT O.MFR
FROM dbo.ORDERS O

INNER JOIN dbo.CUSTOMERS C ON O.CUST_NUM = C.CUST_NUM

WHERE C.COMPANY LIKE '%CORP%'
  AND YEAR(O.ORDER_DATE) = 2008;




SELECT 
    C.CUST_NUM,
    MONTH(O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS

FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 

    ON C.CUST_NUM = O.CUST_NUM
    AND YEAR(O.ORDER_DATE) = 2008

WHERE C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UNIQUE_ORDERS DESC;


SELECT DISTINCT 

    C.CUST_NUM,
    UPPER(C.COMPANY) AS COMPANY_NAME,

    P.DESCRIPTION

FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 

    ON C.CUST_NUM = O.CUST_NUM
    AND YEAR(O.ORDER_DATE) = 2008
LEFT JOIN dbo.PRODUCTS P 

    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE C.COMPANY LIKE '%CORP%';





