SELECT DISTINCT o.MFR
FROM DBO.CUSTOMERS c
INNER JOIN DBO.ORDERS o ON c.CUST_NUM = o.CUST
WHERE o.ORDER_DATE BETWEEN '20080101' AND '20081231'
AND c.COMPANY LIKE '%CORP%';

SELECT 
c.CUST_NUM,
MONTH(o.ORDER_DATE) AS OrderMonth, COUNT (DISTINCT ORDER_NUM) AS UniqueOrders
FROM dbo. CUSTOMERS c
LEFT JOIN dbo.ORDERS O ON c.CUST_NUM = o.CUST
AND o.ORDER_DATE BETWEEN '20080101' AND '20081231'
AND c.COMPANY LIKE '%CORP%'
GROUP BY c.CUST_NUM, MONTH(o.ORDER_DATE)
ORDER BY UniqueOrders DESC;

SELECT 
c.CUST_NUM, UPPER(c.COMPANY) AS CompanyName,
p.DESCRIPTION AS ProductDescription
FROM DBO.CUSTOMERS c
LEFT JOIN DBO.ORDERS o ON c.CUST_NUM = o.CUST AND o.ORDER_DATE BETWEEN '20080101' AND '20081231'
AND c.COMPANY LIKE '%CORP%'
LEFT JOIN DBO.PRODUCTS p ON o.PRODUCT = p.PRODUCT_ID
WHERE c.CUST_NUM IS NOT NULL;
