?/*TASK 1*/
SELECT DISTINCT MFR
FROM DBO.ORDERS O
INNER JOIN DBO.CUSTOMERS C
ON O.REP=C.CUST_REP
WHERE COMPANY LIKE '%CORP%'
AND ORDER_DATE>='20080101'
AND ORDER_DATE<'20090101';

/*TASK 2*/
SELECT 
C.CUST_NUM,
ISNULL(MONTH(O.ORDER_DATE), NULL) AS ORDER_MONTH,
COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 
ON C.CUST_REP = O.REP
AND O.ORDER_DATE >= '2008-01-01' AND O.ORDER_DATE < '2009-01-01'
AND C.COMPANY LIKE '%CORP%'
GROUP BY 
C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UNIQUE_ORDERS DESC;

/*TASK 3*/
SELECT DISTINCT
C.CUST_NUM,
UPPER(C.COMPANY) AS COMPANY_NAME,
P.[DESCRIPTION]
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 
ON C.CUST_REP = O.REP
AND ORDER_DATE>='20080101'
AND ORDER_DATE<'20090101'
AND C.COMPANY LIKE '%CORP%'
LEFT JOIN dbo.PRODUCTS P 
ON O.[PRODUCT] = P.PRODUCT_ID
GROUP BY 
C.CUST_NUM,
UPPER(C.COMPANY),
P.[DESCRIPTION];




SELECT*
FROM DBO.CUSTOMERS
SELECT*
FROM DBO.ORDERS
SELECT*
FROM DBO.PRODUCTS